---
apiVersion: v1
kind: Namespace
metadata:
  name: dockercoins-generic
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hasher
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  targetNamespace: dockercoins-generic
  releaseName: hasher
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rng
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  targetNamespace: dockercoins-generic
  releaseName: rng
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: worker
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  targetNamespace: dockercoins-generic
  releaseName: worker
  values:
    livenessProbe: null
    readinessProbe: null
    service: false  
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webui
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  targetNamespace: dockercoins-generic
  releaseName: webui
  values:
    service:
      type: NodePort
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  targetNamespace: dockercoins-generic
  releaseName: redis
  values:
    service:
      port: 6379
    image:
      repository: redis
      tag: latest
    livenessProbe: null
    readinessProbe: null
