apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- blue.yaml
- ../../../apps/dockercoins-yaml/flux.yaml
#- ../../../apps/APP1/flux.yaml
#- ../../../apps/APP2/flux.yaml
