apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../../apps/dockercoins-yaml/flux.yaml
- ../../../apps/dockercoins-generic/flux.yaml
