---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dockercoins-yaml
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/dockercoins-yaml/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: dockercoins-yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: dockercoins-yaml
